INFO: Starting training:
        Model:              ResNet50
        Epochs:             10
        Batch size:         1
        Learning rate:      0.0001
        Training size:      11350
        validation size:    1261
        validation %:       0.1
        Checkpoints:        True
        Device:             cuda
        Mixed Precision:    False


Epoch 1/10:   0%|▏                                                                                                                                 | 11/11350 [00:17<1:10:02,  2.70img/s, loss (batch)=0.0445]











































Validation set: Average loss: 19.4087, Accuracy: 0.06%
INFO: Validation Dice score: 19.408737182617188, Correct: 0.057097541633624106

Epoch 1/10:   0%|▎                                                                                                                                 | 22/11350 [01:56<3:20:43,  1.06s/img, loss (batch)=0.0462]











































Validation set: Average loss: 0.4496, Accuracy: 0.08%
INFO: Validation Dice score: 0.4495827257633209, Correct: 0.08247422680412371
Epoch 1/10:   0%|▍                                                                                                                                 | 33/11350 [03:37<3:28:25,  1.11s/img, loss (batch)=0.0353]











































Validation set: Average loss: 0.0286, Accuracy: 0.02%
INFO: Validation Dice score: 0.028618233278393745, Correct: 0.023790642347343377

Epoch 1/10:   0%|▌                                                                                                                                 | 44/11350 [05:14<3:22:40,  1.08s/img, loss (batch)=0.0209]




























Traceback (most recent call last):
  File "C:\Python\Python39\lib\multiprocessing\queues.py", line 247, in _feed
    send_bytes(obj)
  File "C:\Python\Python39\lib\multiprocessing\connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Python\Python39\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
INFO: Saved interrupt